/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.24.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export interface InstantiateMsg {
  debug: boolean;
}
export type ExecuteMsg = {
  set_map: {
    key: string;
    value: string;
  };
} | {
  execute_swap_exact_amount_in: {
    routes: SwapAmountInRoute[];
    token_in?: Coin | null;
    token_out_min_amount: string;
  };
};
export interface SwapAmountInRoute {
  pool_id: number;
  token_out_denom: string;
  [k: string]: unknown;
}
export interface Coin {
  amount: string;
  denom: string;
  [k: string]: unknown;
}
export type QueryMsg = {
  query_num_pools: {};
} | {
  query_epochs_info: {};
} | {
  query_pool: {
    pool_id: number;
  };
} | {
  query_pool_params: {
    pool_id: number;
  };
} | {
  query_arithmetic_twap: {
    base_asset: string;
    end_time?: Timestamp | null;
    pool_id: number;
    quote_asset: string;
    start_time?: Timestamp | null;
  };
} | {
  query_map: {
    key: string;
  };
};
export interface Timestamp {
  nanos: number;
  seconds: number;
  [k: string]: unknown;
}
export type MigrateMsg = string;
export interface ArithmeticTwapResponse {
  arithmetic_twap: string;
  [k: string]: unknown;
}
export interface QueryEpochsInfoResponse {
  epochs: EpochInfo[];
  [k: string]: unknown;
}
export interface EpochInfo {
  current_epoch: number;
  current_epoch_start_height: number;
  current_epoch_start_time?: Timestamp | null;
  duration?: Duration | null;
  epoch_counting_started: boolean;
  identifier: string;
  start_time?: Timestamp | null;
  [k: string]: unknown;
}
export interface Duration {
  nanos: number;
  seconds: number;
  [k: string]: unknown;
}
export interface QueryMapResponse {
  value: string;
}
export interface QueryNumPoolsResponse {
  num_pools: number;
  [k: string]: unknown;
}
export interface QueryPoolResponse {
  pool?: Any | null;
  [k: string]: unknown;
}
export interface Any {
  type_url: string;
  value: number[];
  [k: string]: unknown;
}
export interface QueryPoolParamsResponse {
  params?: Any | null;
  [k: string]: unknown;
}